### ISSUE TITLE
How well does it work?

### ISSUE THREAD

**Issue by joq3** [vvpossible/homebridge_yeelight#1]
Hi,

I'm trying to find more information on this plugin. I do not have any Yeelight yet, but I'm thinking of buying it today. I just want to know what features this has got. Does it work fully with Homekit, and can you see the state of the light? That it is turned on or off? Is it possible to dim the light via this plugin.

A little description would be great!

Thank you!

**Comment by bluefoxlee** [comment]
Yes for all of your three questions. 
However do notice that white and color bulb are 220V for now, although it works under 110V(but not bright as 220).

**Comment by joq3** [comment]
Great!

Can you create a wake up scenario? Like a sunrise wakeup light? Is this able to be done via Homekit?

220V is what I have in Sweden, so it is fine! :)

**Comment by bluefoxlee** [comment]
I believe you are talking about automatic in Home app instead of scenriao with it.
I just setup a quick test (base on time although you can choice sun raise/set etc here). And yes it works well too. You can even setup % of he light when it turns on as well. So far so good.

**Comment by ageorgios** [comment]
There is only one limitation.
The homebridge plugin does not read state of the lamp.
Explain why: When you turn off the lamp and turn on again it does not read the correct changed state for example.

**Comment by vvpossible** [comment]
Close this issue because the latest plugin has fixed it.
