### ISSUE TITLE
Config example to show naming lights

### ISSUE THREAD

**Issue by pemontto** [vvpossible/homebridge_yeelight#11]
Can anyone provide a sample config where they have named their lights? I'm not sure how to add settings to lights.

**Comment by txhay4** [comment]
I am not sure if this is what you were after, but you can change your settings and light names in Apple HomeKit directly. Hold the light you want yo change and hHomeKit will give you access to settings.

**Comment by vvpossible** [comment]
close it since it has nothing to do with the plugin iteself
