### ISSUE TITLE
not working the first time

### ISSUE THREAD

**Issue by ageorgios** [vvpossible/homebridge_yeelight#17]
hello,

when the yeelight is off for a long time (usually 7-8 hours) sometimes when I set it to turn on, it doesnt. It needs to turnoff-turnon again to wake up.

**Comment by Stevenyu1982** [comment]
the same issue happened in my environment as well. not sure what's going on, any idea how to get some debug information?

**Comment by Stevenyu1982** [comment]
here is what I see from the log, it seems when long time not using yeelight , it will failed to connect by socket connection, then it will retry again . my guessing the yeelight is somehow idle, it require send some packs to wake up? will check the code ,see if i can fix this, but very newbie at nodejs.  lets see if someone else reply this

May 26 09:42:40 stevenhomesmart homebridge[7491]: socket error
May 26 09:42:40 stevenhomesmart homebridge[7491]: failed to connect!
May 26 09:42:40 stevenhomesmart homebridge[7491]: [5/26/2017, 9:42:40 AM] [yeelight] accesseory unreachable
May 26 09:42:40 stevenhomesmart homebridge[7491]: [5/26/2017, 9:42:40 AM] [yeelight] dev disconnected 0x0000000003426d34 false
May 26 09:42:43 stevenhomesmart homebridge[7491]: retry connect (0) ...: 0x0000000003426d34
May 26 09:42:43 stevenhomesmart homebridge[7491]: connect ok!
May 26 09:42:43 stevenhomesmart homebridge[7491]: [5/26/2017, 9:42:43 AM] [yeelight] accesseory reachable
May 26 09:42:43 stevenhomesmart homebridge[7491]: [5/26/2017, 9:42:43 AM] [yeelight] dev connected 0x0000000003426d34 true
May 26 09:42:45 stevenhomesmart homebridge[7491]: {"id":1,"method":"set_power","params":["off","smooth",500]}
May 26 09:42:47 stevenhomesmart homebridge[7491]: {"id":1,"method":"set_power","params":["on","smooth",500]}
May 26 09:42:47 stevenhomesmart homebridge[7491]: 0x0000000003426d34 property change: power value: 1
May 26 09:42:47 stevenhomesmart homebridge[7491]: [5/26/2017, 9:42:47 AM] [yeelight] update accessory prop: powervalue: 1
May 26 09:42:52 stevenhomesmart homebridge[7491]: {"id":1,"method":"set_power","params":["off","smooth",500]}
May 26 09:42:52 stevenhomesmart homebridge[7491]: 0x0000000003426d34 property change: power value: 0
May 26 09:42:52 stevenhomesmart homebridge[7491]: [5/26/2017, 9:42:52 AM] [yeelight] update accessory prop: powervalue: 0

**Comment by vvpossible** [comment]
Add keepalive mechanism to detect dead TCP connection.

**Comment by ageorgios** [comment]
please make clear what you mean.
Is there a keep alive mechanism somewhere? Or you mean that a keep alive mechanism has to implemented so as to detect dead TCP connection (pull request)?
