### ISSUE TITLE
Cannot turn on the developer mode of MI led Lamp

### ISSUE THREAD

**Issue by TylerYang** [vvpossible/homebridge_yeelight#2]
I just download the **Yeelight** from the ios app store, and **pair connected my MI Led Desk Lamp to this app**. 

As you can see from the screenshot I attached below, there is no such item called `developer mode` in the app. 

SO the quesion is, **how to turn on the developer mode of MI Led Desk Lamp?**
![2ae33da6-ff31-45e0-95cc-64e721f72bdf](https://cloud.githubusercontent.com/assets/5443053/20265981/f87c907c-aaae-11e6-8ffc-eb4b7b2bb216.png)

**Comment by Sagwed** [comment]
Turn on "Geek Mode" in Andriod version Yeelignt App

**Comment by vvpossible** [comment]
MI LED Desk Lamp doesn't support Developer mode due to policy issue, sorry for that.

**Comment by TylerYang** [comment]
@vvpossible Any plan for enable the developer mode in the future?

**Comment by vvpossible** [comment]
No, I don't think we will support developer mode on Mi LED Desk Lamp.

**Comment by TylerYang** [comment]
That hurts.

**Comment by justme-1968** [comment]
this is very disappointing. just bought the lamp to integrate it into my home automation system. but without the developer mode it is useless...

**Comment by TylerYang** [comment]
@justme-1968 +1

**Comment by alexeyshulzhenko** [comment]
@justme-1968 +1 Sad to heat that

**Comment by theo-69** [comment]
mine is working

![img_9093cc6c1dcb-1](https://user-images.githubusercontent.com/28484958/40730662-33636da6-63fd-11e8-9aa9-59b0b233285a.jpeg)

**Comment by xiaohk** [comment]
For Yeelight iOS app (version 3.3.31), you **cannot** turn on LAN control for desk lamp 1 on device control panel (left screenshot), but you **can** turn it on directly from the LAN control menu (menu => LAN Control), see the right screenshot.

![test](https://user-images.githubusercontent.com/15007159/103302840-94013900-49d2-11eb-9698-f72805a372b3.png)
