### ISSUE TITLE
It does not read state after turning off->on

### ISSUE THREAD

**Issue by ageorgios** [vvpossible/homebridge_yeelight#3]
When you turn off the lamp and then on again, it goes to a given state different than before. The homebridge plugin does not recognize this change of state.

**Comment by vvpossible** [comment]
Do you mean cut the power of the lamp? If that's the case, since the device is totally offline, I can't tell whether it's powered off or just lost connection. 
If you mean softly turn on/off the lamp by anther app, I think this case has been handled, please try again and let me know.

**Comment by ageorgios** [comment]
Thank you for your great work!

I just checked and if you change the percentage of dimming for example from the Yeelight app it does not change in iOS HomeKit.

**Comment by vvpossible** [comment]
Did you upgrade your homebridge-yeelight to the latest version? I have fixed this issue weeks ago. I just tested it and it works as expected...

**Comment by ageorgios** [comment]
used npm i -g homebridge-yeelight and got
homebridge-yeelight@0.0.14
