### ISSUE TITLE
Why continuously like this?

### ISSUE THREAD

**Issue by eviewei** [vvpossible/homebridge_yeelight#31]
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x000000000361c09f
{"id":-1,"method":"get_prop","params":["power"]}

**Comment by maragelis** [comment]
edit the yee.js and add // to every console.log statement

**Comment by eviewei** [comment]
Temporary solution
