### ISSUE TITLE
This one can work with ha bridge?

### ISSUE THREAD

**Issue by mp3llll** [vvpossible/homebridge_yeelight#4]
Hello

I have amazon echo and ha bridge on resbari can i use this one to off on the yeelight?

**Comment by vvpossible** [comment]
You can install homebridge & this plugin on your Raspberry Pi and then you will be able to control Yeelight by Siri.

**Comment by mp3llll** [comment]
Notice I'm talking about ha bridge and not Home bridge.

There is way to add it to my ha bridge with my Raspberry

**Comment by vvpossible** [comment]
I'm not familiar with HA bridge, if it support plugin mechanism, then by following Yeelight open protocol, it surely can be integrated.
