### ISSUE TITLE
How to remove Yeelight?

### ISSUE THREAD

**Issue by jannnfe** [vvpossible/homebridge_yeelight#44]
Hello,
how to remove the Yeelight from HomeKit?
Thanks!

**Comment by PatchworkBoy** [comment]
```
cd /usr/local/lib/node_modules
sudo rm -rf homebridge-yeelight
```

then edit your homebridge config.json and remove the following from your platforms:
```
       {
            "platform" : "yeelight",
            "name" : "yeelight"
        }
```

Restart homebridge

**Comment by jannnfe** [comment]
Sorry my fault, I just deleted the entry from the config.json but did not remove the plugin. Thank you!
