### ISSUE TITLE
6 yeelights bulb but only appear yeebridge in homekit

### ISSUE THREAD

**Issue by garvarma** [vvpossible/homebridge_yeelight#5]
Hi, 
I have 6 yeelight (5 white and 1 rgb) and when i add the component into homekit, only appears a yeebridge device, but not each of yeelights that i have it.

What i,m doing wrong? Maybe file config.json must have something else?

Thanks

**Comment by vvpossible** [comment]
Did you open developer mode of your bulbs? If not, please search and download "Yeelight" app and go to settings to turn on the option.

**Comment by garvarma** [comment]
Hi, 
Yes i have all in developer mode, because all one works on homeassistant.
I think that i know where is problem, but first i'm trying to check one thing

I will tell you if i resolv the problem.

thanks

**Comment by Sunbelife** [comment]
@garvarma have you solve your problem? i have the same problem with you.

**Comment by vvpossible** [comment]
If you are using router with Openwrt, please check this out and see if it can solve your issue.
http://forum.yeelight.com/t/python/69/9

**Comment by Sunbelife** [comment]
@vvpossible I using my raspberry Pi.
i can find homebridge device, but i can't find yeelight.

Here's log after running homebridge
```

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[12/28/2016, 7:24:27 PM] Loaded plugin: homebridge-yeelight
[12/28/2016, 7:24:27 PM] Registering platform 'homebridge-yeelight.yeelight'
[12/28/2016, 7:24:27 PM] ---
[12/28/2016, 7:24:27 PM] Loaded config.json with 0 accessories and 1 platforms.
[12/28/2016, 7:24:27 PM] ---
[12/28/2016, 7:24:28 PM] Loading 1 platforms...
[12/28/2016, 7:24:28 PM] [yeelight] Initializing yeelight platform...
[12/28/2016, 7:24:28 PM] [yeelight] YeePlatform Init
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/28/2016, 7:24:28 PM] [yeelight] DidFinishLaunching
[12/28/2016, 7:24:28 PM] Homebridge is running on port 51825.
add to multicast group
listen on 0.0.0.0
no did or loc found!
```

**Comment by vvpossible** [comment]
That means Yeelight app can't find the bulb through a multicast UDP message. Please check my last comments and see if your router is using Openwrt. 
You may also try other demo apps from here "https://www.yeelight.com/en_US/developer". If they can find the bulbs, so does Yeelight homebridge plugin.

**Comment by garvarma** [comment]
Hi,
Yes in my case i solve problem.
My problem was that i have 2 networks at home, 1 for devices and other for domotic.
The problem was that my lights bulbs where in 1 network and homekit gateway (ipad) in different network. Once that ipad was in the same network as bulbs, then all works well

**Comment by Sunbelife** [comment]
@garvarma i already check my Wi-Fi connection.. they are in the same network,y_y

@vvpossible my router isn't using Openwrt, must i use a Openwrt router?
i run the demo app and found nothing.. but my phone can control my bulb.

**Comment by vvpossible** [comment]
No, any router should work. Is your phone connecting to 5G, that could cause some issue.

**Comment by Sunbelife** [comment]
@vvpossible No. my router have only 2.4G..

**Comment by Sunbelife** [comment]
i have successed before on another router. but this router which i use now still can't work.

**Comment by vvpossible** [comment]
OK, seems it's related to your router. Could you logon to your router and see if there is some IGMP related settings.

**Comment by Sunbelife** [comment]
Nothing can be found related to IGMP settings... it's looks seem i need to replace a router..

**Comment by Sunbelife** [comment]
You know what?
it works immediately when i change to another router..

```
pi@raspberrypi:/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[12/29/2016, 4:30:45 AM] Loaded plugin: homebridge-yeelight
[12/29/2016, 4:30:45 AM] Registering platform 'homebridge-yeelight.yeelight'
[12/29/2016, 4:30:45 AM] ---
[12/29/2016, 4:30:45 AM] Loaded config.json with 0 accessories and 1 platforms.
[12/29/2016, 4:30:45 AM] ---
[12/29/2016, 4:30:45 AM] Loading 1 platforms...
[12/29/2016, 4:30:45 AM] [yeelight] Initializing yeelight platform...
[12/29/2016, 4:30:45 AM] [yeelight] YeePlatform Init
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/29/2016, 4:30:45 AM] [yeelight] DidFinishLaunching
[12/29/2016, 4:30:45 AM] Homebridge is running on port 51825.
add to multicast group
listen on 0.0.0.0
no did or loc found!
[12/29/2016, 4:30:45 AM] [yeelight] cached accessory: 0x0000000002e031a1
already in device list!
connect ok!
[12/29/2016, 4:30:45 AM] [yeelight] accesseory reachable
[12/29/2016, 4:30:45 AM] [yeelight] dev connected 0x0000000002e031a1 true
```


thanks for you answer and patient.

(but i can't found home bridge in home App now, I'm working on it.)
