### ISSUE TITLE
Yeelight doens't seem to work with rules

### ISSUE THREAD

**Issue by adekka** [vvpossible/homebridge_yeelight#6]
I have three Yeelights set up via homebridge. All show up perfectly and I can turn them on and off them via e.g. the Eve App. However, when I user them in a scene combined with a rule it somehow doens't work. 

I have a rule that says: if the Xiaomi door sensor notice that a door is opened, trigger the scene where a Yeelight is turned on. Via the Eve app is see that the sensor indicates a door is opened. The yeelight however doesn't respond. Any clue what is going on?

**Comment by vvpossible** [comment]
Please fix one end and try. For example, use the door sensor to trigger other device type. Or use other sensor to trigger Yeelight device. With this test, you may find the root cause. You may also try create a scene with Yeelight and click to trigger it.

**Comment by adekka** [comment]
Seems to be a problem with the Aqara plugin.. thx anyway!
