### ISSUE TITLE
How can i enable developer mode on yeelight ?

### ISSUE THREAD

**Issue by dimiandre** [vvpossible/homebridge_yeelight#7]
How can i enable developer mode on yeelight ?

in the latest version of mi home i can't find the option..

**Comment by vvpossible** [comment]
Search and download "Yeelight" app, the developer mode option is only available there.

**Comment by ryanerwin** [comment]
FYI, this is the top search result for "how to enable developer mode on yeelight"

The option has been renamed to "LAN Control"
In the Yeelight app, once you've selected your device, click the "Eject" looking icon on the bottom right and you'll see a menu including "LAN Control"... Open "LAN Control" and enable it.
